#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
static NSString*const P=@"/var/mobile/VMLHostSniffer.txt";static UIView*g=nil;
static void L(NSString*f,...){va_list a;va_start(a,f);NSString*m=[[NSString alloc]initWithFormat:f arguments:a];va_end(a);NSString*s=[NSString stringWithFormat:@"[CLONE-ABOVEHOST-16.64] %@\n",m?:@""];NSFileHandle*h=[NSFileHandle fileHandleForWritingAtPath:P];if(!h)[s writeToFile:P atomically:YES encoding:NSUTF8StringEncoding error:nil];else @try{[h seekToEndOfFile];[h writeData:[s dataUsingEncoding:NSUTF8StringEncoding]];[h closeFile];}@catch(__unused NSException*e){}}
static void PutAbove(UIView*host){UIView*p=host.superview;if(!p||!host.window)return;CGRect b=p.bounds;if(b.size.width<150||b.size.height<150)return;if(g)[g removeFromSuperview];g=[[UIView alloc]initWithFrame:CGRectMake(MAX(4,b.size.width-90),8,82,82)];g.backgroundColor=UIColor.systemYellowColor;g.layer.cornerRadius=41;g.layer.borderWidth=7;g.layer.borderColor=UIColor.systemGreenColor.CGColor;g.userInteractionEnabled=NO;UILabel*l=[[UILabel alloc]initWithFrame:g.bounds];l.text=@"64";l.textAlignment=NSTextAlignmentCenter;l.font=[UIFont boldSystemFontOfSize:27];l.textColor=UIColor.blackColor;[g addSubview:l];[p insertSubview:g aboveSubview:host];g.layer.zPosition=1000000;L(@"INSERTED ABOVE host=%p parent=%@ hostFrame=%@ parentFrame=%@ indexHost=%lu index64=%lu window=%@",host,NSStringFromClass(p.class),NSStringFromCGRect(host.frame),NSStringFromCGRect(p.frame),(unsigned long)[p.subviews indexOfObject:host],(unsigned long)[p.subviews indexOfObject:g],NSStringFromClass(host.window.class));}
%hook _UIContextLayerHostView
-(void)didMoveToSuperview{%orig;UIView*h=(UIView*)self;if(h.superview&&h.window)dispatch_async(dispatch_get_main_queue(),^{PutAbove(h);});}
%end
%ctor{@autoreleasepool{if(![NSBundle.mainBundle.bundleIdentifier isEqualToString:@"com.apple.CarPlayApp"])return;L(@"CLONE ABOVE-HOST TEST 16.64 ACTIVE");}}
